# Android Switch Class Driver
obj-$(CONFIG_ANDROID_SWITCH)		+= switch_class.o
obj-$(CONFIG_SWITCH_HEADSET)+= switch_headset.o
obj-$(CONFIG_ANDROID_SWITCH_GPIO)	+= switch_gpio.o
obj-$(CONFIG_SUNXI_SWITCH_HEADSET)	+= switch_headset_sunxi.o 

